---
abstract: 'Simple initialization for command-line scripts'
author:
  - 'Len Budney <len.budney@gmail.com>'
build_requires:
  Test::Exception: 0
  Test::More: 0
  Test::Trap: 0
configure_requires:
  Module::Build: 0.33
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CLI-Startup
provides:
  CLI::Startup:
    file: lib/CLI/Startup.pm
    version: 0.03
requires:
  Class::Std: 0.01
  Clone: 0
  Config::Simple: 4.58
  File::Basename: 0
  Getopt::Long: 2.38
  Hash::Merge: 0
  List::Util: 0
  Pod::Text: 0
  Text::CSV: 0
  perl: v5.8.8
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
